# Generated by Django 5.2.4 on 2025-07-14 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteEstoque',
            fields=[
                ('ajuste_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_ajuste', models.CharField(choices=[('entrada_inventario', 'Entrada de Inventário'), ('saida_inventario', 'Saída de Inventário'), ('perda', 'Perda'), ('quebra', 'Quebra'), ('devolucao_fornecedor', 'Devolução ao Fornecedor'), ('outros_entrada', 'Outros (Entrada)'), ('outros_saida', 'Outros (Saída)')], max_length=30)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('ajustado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('fornecedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('contato_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('contato_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contato_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('item_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_pedida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_recebida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizacaoEstoque',
            fields=[
                ('localizacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoteProduto',
            fields=[
                ('lote_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=100)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('movimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_movimento', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('movimentado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('pedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recebido_parcial', 'Recebido Parcial'), ('recebido_total', 'Recebido Total'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('total_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel_minimo_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('fator_conversao', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
            ],
        ),
    ]
