# Generated by Django 5.2.4 on 2025-07-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('estoque', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacaoestoque',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacoes_estoque', to='clinica.clinica'),
        ),
    ]
