# Generated by Django 5.2.4 on 2025-07-14 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('sobrenome', models.CharField(db_index=True, max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True)),
                ('perfil_epidemiologico', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimentoPaciente',
            fields=[
                ('consentimento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_consentimento', models.CharField(max_length=50)),
                ('data_consentimento', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelLegal',
            fields=[
                ('responsavel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('grau_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPaciente',
            fields=[
                ('documento_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dados_ocr', models.TextField(blank=True, null=True)),
                ('caminho_arquivo', models.FileField(upload_to='documentos_pacientes/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='paciente.paciente')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.tipodocumento')),
            ],
        ),
    ]
