# Generated by Django 5.2.4 on 2025-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='clinicas',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='clinica.clinica'),
        ),
    ]
