# Generated by Django 5.2.4 on 2025-07-14 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('clinica', '0001_initial'),
        ('paciente', '0002_paciente_clinicas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('prontuario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuario', to='agendamento.agendamento')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_aluno', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='clinica.clinica')),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_coordenador', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='AnexoProntuario',
            fields=[
                ('anexo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_anexo', models.CharField(blank=True, max_length=50, null=True)),
                ('caminho_arquivo', models.FileField(upload_to='prontuarios/anexos/')),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='prontuario.prontuario')),
            ],
            options={
                'verbose_name': 'Anexo de Prontuário',
                'verbose_name_plural': 'Anexos de Prontuários',
            },
        ),
        migrations.CreateModel(
            name='VersaoProntuario',
            fields=[
                ('versao_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anotacoes', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_prontuario_aluno', to=settings.AUTH_USER_MODEL)),
                ('coordenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_prontuario_coordenador', to=settings.AUTH_USER_MODEL)),
                ('prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='prontuario.prontuario')),
            ],
            options={
                'verbose_name': 'Versão de Prontuário',
                'verbose_name_plural': 'Versões de Prontuários',
                'ordering': ['criado_em'],
            },
        ),
    ]
