"""Add missing motivo_falha column to logs_acesso

Revision ID: 53f52c402233
Revises: 0bc04ea374fb
Create Date: 2025-07-15 21:08:26.144128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f52c402233'
down_revision: Union[str, Sequence[str], None] = '0bc04ea374fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
