# Generated by Django 5.2.4 on 2025-07-14 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('paciente', '0002_paciente_clinicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadeFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(help_text='Nível de prioridade (menor número = maior prioridade)', unique=True)),
            ],
            options={
                'verbose_name': 'Prioridade de Fila',
                'verbose_name_plural': 'Prioridades de Fila',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='FilaEspera',
            fields=[
                ('fila_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_fila', models.IntegerField(help_text='Número sequencial na fila')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('em_atendimento', 'Em Atendimento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_espera', to='clinica.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_espera', to='paciente.paciente')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filas_espera', to='fila.prioridadefila')),
            ],
            options={
                'verbose_name': 'Fila de Espera',
                'verbose_name_plural': 'Filas de Espera',
                'ordering': ['criado_em'],
            },
        ),
    ]
