# Generated by Django 5.2.4 on 2025-07-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clinicas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='clinica.clinica'),
        ),
    ]
