# Generated by Django 5.2.4 on 2025-07-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_clinicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_schedule_appointment', 'Pode agendar consultas'), ('can_attend_clinic', 'Pode atender em clínicas'), ('can_manage_prontuario', 'Pode gerenciar prontuários')]},
        ),
    ]
