# Generated by Django 5.2.4 on 2025-07-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='tipo',
            field=models.CharField(choices=[('FISIOTERAPIA', 'Fisioterapia'), ('ODONTOLOGIA', 'Odontologia'), ('PILATES', 'Pilates'), ('RAIO_X', 'Raio-X'), ('FARMACIA', 'Farmácia'), ('ESTETICA', 'Estética'), ('PSICOLOGIA', 'Psicologia'), ('NUTRICAO', 'Nutrição'), ('JURIDICO', 'Jurídico'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
    ]
