# Generated by Django 5.2.4 on 2025-07-14 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('clinica', '0002_clinica_tipo'),
        ('paciente', '0003_paciente_cpf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('atendimento_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('em_progresso', 'Em Progresso'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='iniciado', max_length=50)),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('saida', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento', to='agendamento.agendamento')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clinica.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
